### ISSUE TITLE
Change language on website

### ISSUE THREAD

**Issue by MimiOnuoha** [ritughiya/ritughiya.github.io#6]
Right now the website says "over two days, the first ever New York Tech Zine Fair (NYTZF) will provide a platform..." this is misleading, it's really just one day + VIP event.  Should just say "On December 1st, the first ever New York..." and then at the bottom we can add "join us on november 30 for the vip event" and link to the ticket.

**Comment by tchoi8** [comment]
https://github.com/ritughiya/ritughiya.github.io/commit/db62134fdd44029a86061c6d1d07eaa3fa258c48
